import { OnInit } from '@angular/core';
import { Component } from '@angular/core';


@Component({
    selector: 'app-input-button-unit',
    template: `
            <p>
                input-button-unit works!
                The title is: {{ title }}
            </p>

            <input [value]="title" 
            (keyup.enter)="changeTitle($event)">
    `,
    styleUrls: ['./input-button-unit.component.css']
})
export class InputButtonUnitComponent implements OnInit{
    
    title = 'Digite sua tarefa';

  constructor() {}

  generateTitle(): string {
    return 'This title was generated by a method.';
  }

  changeTitle(event): void {
    console.log(event);
    this.title = event.target.value; // A funcionalidade original ainda funciona!
  }

  ngOnInit() {
    setTimeout(() => {
        this.title = 'Digite sua tarefa';
      }, 3000);
  }
  
}
